foreground #e8e8e8
background #252525
selection_foreground #252525
selection_background #e8e8e8
background_opacity 0.85

cursor #e8e8e8
cursor_text_color #252525

active_border_color #8d8d8d
active_tab_background #8d8d8d

color0 #252525
color1 #a4a4a4
color2 #b6b6b6
color3 #cecece
color4 #8d8d8d
color5 #9b9b9b
color6 #b0b0b0
color7 #ececec
color8 #4a4a4a
color9 #a4a4a4
color10 #b6b6b6
color11 #cecece
color12 #8d8d8d
color13 #9b9b9b
color14 #b0b0b0
color15 #ffffff
