# Workspace autostart
exec-once = [workspace 1 silent] uwsm-app -- firefox
exec-once = [workspace 2 silent] uwsm-app -- xdg-terminal-exec
exec-once = [workspace 2 silent] uwsm-app -- xdg-terminal-exec
exec-once = [workspace 3 silent] flatpak run com.discordapp.Discord --force-device-scale-factor=0.7
exec-once = [workspace 4 silent] uwsm-app -- spotify --force-device-scale-factor=0.7
